version: '3.6'

services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./sql/sre-challenge-addon1.sql:/docker-entrypoint-initdb.d/init.sql

  buckets:
    image: minio/minio:RELEASE.2022-04-16T04-26-02Z
    command: "server /data --console-address :9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: "${AWS_ACCESS_KEY_ID}"
      MINIO_ROOT_PASSWORD: "${AWS_SECRET_ACCESS_KEY}"
    volumes:
      - bucketdata:/data

volumes:
  dbdata:
  bucketdata:
